version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    image: chienpm1/cinema_web:latest
    container_name: cinema_web
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY} 
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DATABASE_URL=${DATABASE_URL}

  sidekiq:
    image: chienpm1/cinema_web:latest
    container_name: cinema_sidekiq
    command: bundle exec sidekiq 
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DATABASE_URL=${DATABASE_URL}

volumes:
  redis_data: